<?php

	//application details
		$apps[$x]['name'] = "Power Saving";
		$apps[$x]['uuid'] = "7515138b-d6e1-430c-8acb-87fe930ceea8";
		$apps[$x]['category'] = "Vendor";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "Configure Phone Power Saving Options.";
		$apps[$x]['description']['en-gb'] = "Configure Phone Power Saving Options.";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "";
		$apps[$x]['description']['es-cl'] = "";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "";
		$apps[$x]['description']['fr-fr'] = "";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['nl-nl'] = "";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";

	//permission details
		$y=0;
		$apps[$x]['permissions'][$y]['name'] = "power_saving_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "fac58202-4f06-4c92-98e5-927c0c385a36";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;

	//default settings
		$y=0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "de06146d-6af7-42f3-bf4d-11e9bac9ffb9";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_enabled";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable Yealink Power Saving enables or disables the power saving intelligent mode.";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "7190b4dc-0664-4b7a-bbdc-d006e5ef8950";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_led_on";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "500";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set period of time (in ms) when power LED indicator is on in power saving mode. (Range 100-10000)";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "572a26fc-155d-4742-b507-52a68d21c02d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_led_off";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "3000";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set period of time (in ms) when power LED indicator is off in power saving mode. (Range 100-10000)";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c4d5322a-14b3-4448-a0ef-c41ed0751a0c";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_intel_mode";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "1";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
        $apps[$x]['default_settings'][$y]['default_setting_description'] = "Enable Yealink power saving intelligent mode.";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "09ad4a0c-c907-43b8-8721-9ac04451c717";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_idle_timeout";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "10";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set minimum time (in minutes) to wait in the idle state, after using the phone, before the phone enters power saving mode. (Range 1-30)";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "e04a7776-14cc-4828-aa97-43782490fd42";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_offhour_timeout";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "10";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set time (in minutes) to wait in the idle state (during none-office hours), after using the phone, before the phone enters power saving mode. (Range 1-30)";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4cd23612-1db3-4152-bc61-66fb0cd2ee9a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_hour_timeout";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "numeric";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "960";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set time (in minutes) to wait in the idle state (during office hours), after using the phone, before the phone enters power saving mode. (Range 1-30)";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "9567a2d9-1f52-4282-9d67-d64d11995f52";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_days_all";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for all days using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "4c9e390f-cc34-45f9-a678-1011aeafded8";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_days_workweek";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for mon-fri using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "9fc5afd4-a7dd-4600-9db5-8c750848f63f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_day_monday";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for monday using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "c20a49cd-006d-4f18-975e-4515bf0bfb3e";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_day_tuesday";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for tuesday using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "62176d87-9f94-4477-9e96-ccbb477a6a20";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_day_wednesday";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for wednesday using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "7c35d0e1-7544-480f-b6f2-c5c89bdb147b";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_day_thursday";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for thursday using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b676a8b1-be3d-44e5-b399-2ddaa5f08fa4";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_day_friday";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for friday using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "43cabb4f-6546-4718-813a-72b98c961e25";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_day_saturday";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for saturday using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
        $apps[$x]['default_settings'][$y]['default_setting_uuid'] = "6551ae31-bc83-4214-a671-9f51c35d7f8f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "provision";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "yealink_ps_day_sunday";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "8,18";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "false";
        $apps[$x]['default_settings'][$y]['default_setting_description'] = "Yealink set the time for sunday using 24 hour HH,MM format (Example 8AM to 6PM would be 8,18)(Overrides all times)(Do not use 24) ";
        $y++;
?>
